spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: kt7ymZwjLvtk!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

    application:
      security:
        jwt:
          secret-key: 5267556B58703273357638792F413F4428472B4B6250655368566D5971337436
          expiration: 86400000 # a day
          refresh-token:
            expiration: 604800000 # 7 days